#ifndef QTBROWSER_GLOBALS_HH
#define QTBROWSER_GLOBALS_HH

#define ORIENTATION_INITIAL (Qt::Orientation)0

#define EVENT_HELP 1001
#define EVENT_REQUEST_LONG_BEGIN 1010
#define EVENT_REQUEST_LONG_END   1011

#endif
